name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: "CI Test"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout/Clone the repository
        uses: actions/checkout@v2

      - name: Install package
        run: |
          pip install .[docs,tests,curate] codecov regex
          mkdir deps # For QCSchems
          mkdir test_wdir # Working directory to run tests from
                          # (testing installed BSE, not the source tree)

      - name: Install QCSchema HEAD
        working-directory: ./test_wdir
        run: |
          git clone https://github.com/molssi/QCSchema.git
          pip install -e ./QCSchema

      - name: Run tests
        working-directory: ./test_wdir # Move to an unrelated dir and test the installed package
        run: |
          pytest --pyargs --cov=basis_set_exchange --cov-report=xml basis_set_exchange 
          bse -V # Quick test of the cli

      - name: Run documentation tests
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./doc
        run: |
          ln -s ../basis_set_exchange/tests/fakedata ${HOME}/my_data_dir
          mkdir _static
          make doctest
          make html

      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./test_wdir/coverage.xml
          fail_ci_if_error: true
